# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-31 03:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u2f_server', '0002_auto_20160330_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='key_handle',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='user',
            name='public_key',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
